### ISSUE TITLE
Fix the BII-S-1 gist-Demo for ISATab Viewer 

### ISSUE THREAD

**Issue by sneumann** [ISA-tools/ISATab-Viewer#9]
Currently, http://www.antarctic-design.co.uk/isafiles/isaviewer-demo.html 
shows no data. Yours, Steffen

**Comment by djcomlab** [comment]
Hi Steffen, I put a fix in the repo, but it's not been pushed out yet (same problem on http://www.isa-tools.org/format/examples/ but all of our infrastructure went down for a few days). Will see if I can get this deployed asap

**Comment by djcomlab** [comment]
Related to issue #7
